export const actionType = {
    ALL_PRODUCTS_REQUEST : 'ALL_PRODUCTS_REQUEST',
    ALL_PRODUCTS_SUCCESS : 'ALL_PRODUCTS_SUCCESS',
    ALL_PRODUCTS_FAIL : 'ALL_PRODUCTS_FAIL',

    PRODUCT_DETAILS_REQUEST : 'PRODUCT_DETAILS_REQUEST',
    PRODUCT_DETAILS_SUCCESS : 'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_FAIL : 'PRODUCT_DETAILS_FAIL',

    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL : "USER_REGISTER_FAIL",

    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL : "USER_LOGIN_FAIL",

    USER_LOAD_REQUEST : "USER_LOAD_REQUEST",
    USER_LOAD_SUCCESS : "USER_LOAD_SUCCESS",
    USER_LOAD_FAIL : "USER_LOAD_FAIL",

    USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_FAIL : "USER_LOGOUT_FAIL",

    UPDATE_PROFILE_REQUEST : "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS : "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL : "UPDATE_PROFILE_FAIL",

    UPDATE_EMAIL_REQUEST : "UPDATE_EMAIL_REQUEST",
    UPDATE_EMAIL_SUCCESS : "UPDATE_EMAIL_SUCCESS",
    UPDATE_EMAIL_FAIL : "UPDATE_EMAIL_FAIL",
    
    RESET_PASSWORD_REQUEST : "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS : "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL : "RESET_PASSWORD_FAIL",

    FORGET_PASSWORD_REQUEST : "FORGET_PASSWORD_REQUEST",
    FORGET_PASSWORD_SUCCESS : "FORGET_PASSWORD_SUCCESS",
    FORGET_PASSWORD_FAIL : "FORGET_PASSWORD_FAIL",

    CHECK_IN_WISHLIST_REQUEST : "CHECK_IN_WISHLIST_REQUEST",
    CHECK_IN_WISHLIST_SUCCESS : "CHECK_IN_WISHLIST_SUCCESS",
    CHECK_IN_WISHLIST_FAIL : "CHECK_IN_WISHLIST_FAIL",

    ADD_IN_WISHLIST_REQUEST : "ADD_IN_WISHLIST_REQUEST",
    ADD_IN_WISHLIST_SUCCESS : "ADD_IN_WISHLIST_SUCCESS",
    ADD_IN_WISHLIST_FAIL : "ADD_IN_WISHLIST_FAIL",
    
    REMOVE_IN_WISHLIST_REQUEST : "REMOVE_IN_WISHLIST_REQUEST",
    REMOVE_IN_WISHLIST_SUCCESS : "REMOVE_IN_WISHLIST_SUCCESS",
    REMOVE_IN_WISHLIST_FAIL : "REMOVE_IN_WISHLIST_FAIL",
    
    WISHLIST_PRODUCTS_REQUEST : "WISHLIST_PRODUCTS_REQUEST",
    WISHLIST_PRODUCTS_SUCCESS : "WISHLIST_PRODUCTS_SUCCESS",
    WISHLIST_PRODUCTS_FAIL : "WISHLIST_PRODUCTS_FAIL",

    ADD_IN_CART : "ADD_IN_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    CLEAR_DATA_CART : "CLEAR_DATA_CART",

    SAVE_SHIPPING_INFO : "SAVE_SHIPPING_INFO",

    CREATE_ORDER_REQUEST : "CREATE_ORDER_REQUEST",
    CREATE_ORDER_SUCCESS : "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL : "CREATE_ORDER_FAIL",

    ORDERS_REQUEST : "ORDERS_REQUEST",
    ORDERS_SUCCESS : "ORDERS_SUCCESS",
    ORDERS_FAIL : "ORDERS_FAIL",

    CLEAR_DATA : "CLEAR_DATA",

    DASHBOARD_DATA_REQUEST : "DASHBOARD_DATA_REQUEST", 
    DASHBOARD_DATA_SUCCESS : "DASHBOARD_DATA_SUCCESS", 
    DASHBOARD_DATA_FAIL : "DASHBOARD_DATA_FAIL", 

    ALL_PRODUCTS_DASHBOARD_REQUEST : "ALL_PRODUCTS_DASHBOARD_REQUEST",
    ALL_PRODUCTS_DASHBOARD_SUCCESS : "ALL_PRODUCTS_DASHBOARD_SUCCESS",
    ALL_PRODUCTS_DASHBOARD_FAIL : "ALL_PRODUCTS_DASHBOARD_FAIL",

    ADD_PRODUCTS_DASHBOARD_REQUEST : "ADD_PRODUCTS_DASHBOARD_REQUEST",
    ADD_PRODUCTS_DASHBOARD_SUCCESS : "ADD_PRODUCTS_DASHBOARD_SUCCESS",
    ADD_PRODUCTS_DASHBOARD_FAIL : "ADD_PRODUCTS_DASHBOARD_FAIL",

    UPDATE_PRODUCTS_DASHBOARD_REQUEST : "UPDATE_PRODUCTS_DASHBOARD_REQUEST",
    UPDATE_PRODUCTS_DASHBOARD_SUCCESS : "UPDATE_PRODUCTS_DASHBOARD_SUCCESS",
    UPDATE_PRODUCTS_DASHBOARD_FAIL : "UPDATE_PRODUCTS_DASHBOARD_FAIL",
    
    REMOVE_PRODUCTS_DASHBOARD_REQUEST : "REMOVE_PRODUCTS_DASHBOARD_REQUEST",
    REMOVE_PRODUCTS_DASHBOARD_SUCCESS : "REMOVE_PRODUCTS_DASHBOARD_SUCCESS",
    REMOVE_PRODUCTS_DASHBOARD_FAIL : "REMOVE_PRODUCTS_DASHBOARD_FAIL",

    ALL_USERS_DASHBOARD_REQUEST : "ALL_USERS_DASHBOARD_REQUEST",
    ALL_USERS_DASHBOARD_SUCCESS : "ALL_USERS_DASHBOARD_SUCCESS",
    ALL_USERS_DASHBOARD_FAIL : "ALL_USERS_DASHBOARD_FAIL",

    UPDATE_ROLE_DASHBOARD_REQUEST : "UPDATE_ROLE_DASHBOARD_REQUEST",
    UPDATE_ROLE_DASHBOARD_SUCCESS : "UPDATE_ROLE_DASHBOARD_SUCCESS",
    UPDATE_ROLE_DASHBOARD_FAIL : "UPDATE_ROLE_DASHBOARD_FAIL",

    REMOVE_USERS_DASHBOARD_REQUEST : "REMOVE_USERS_DASHBOARD_REQUEST",
    REMOVE_USERS_DASHBOARD_SUCCESS : "REMOVE_USERS_DASHBOARD_SUCCESS",
    REMOVE_USERS_DASHBOARD_FAIL : "REMOVE_USERS_DASHBOARD_FAIL",

    ALL_ORDERS_DASHBOARD_REQUEST : "ALL_ORDERS_DASHBOARD_REQUEST",
    ALL_ORDERS_DASHBOARD_SUCCESS : "ALL_ORDERS_DASHBOARD_SUCCESS",
    ALL_ORDERS_DASHBOARD_FAIL : "ALL_ORDERS_DASHBOARD_FAIL",

    UPDATE_ORDER_DASHBOARD_REQUEST : "UPDATE_ORDER_DASHBOARD_REQUEST",
    UPDATE_ORDER_DASHBOARD_SUCCESS : "UPDATE_ORDER_DASHBOARD_SUCCESS",
    UPDATE_ORDER_DASHBOARD_FAIL : "UPDATE_ORDER_DASHBOARD_FAIL",

    OPEN_PAGE : "OPEN_PAGE",
    CLOSE_PAGE : "CLOSE_PAGE",

    POP_MESSAGE_OPEN : "POP_MESSAGE_OPEN",
    POP_MESSAGE_CLOSE : "POP_MESSAGE_CLOSE",

    CLEAR_ERRORS : 'CLEAR_ERRORS',
}